### ISSUE TITLE
Not Working - Dell Optiplex 745

### ISSUE THREAD

**Issue by totalgaara** [chris1111/BCM5722D#1]
Hi, i tried that kext on my dell optiplex 745macintosh but unfortunatly, no cable detected, what can be the issue ? (The network card is on your list) BCM5754

**Comment by chris1111** [comment]
check your device ID

**Comment by totalgaara** [comment]
Yesterday for no reason it was working and seems my device id is already set.

The strange things it's after a while it doesn't work anymore, no cable detected, after a reboot it come back again but not always. I tested the network card with a live cd of Windows and everything seems to be fine with it :|

**Comment by chris1111** [comment]
So its a Hackintosh issue

**Comment by totalgaara** [comment]
Fixed :) was a short between the case and ethernet port, don't know why  but after fixing, no issue anymore

**Comment by chris1111** [comment]
Ok thanks
