### ISSUE TITLE
MAC Adress 00:00:00:00:00:00

### ISSUE THREAD

**Issue by Dniel97** [chris1111/BCM5722D#2]
Sometimes my Hackintosh gets an MAC Adress and sometimes it says "00:00:00:00:00:00" instead of the original MAC Adress. I have an NetExtreme BCM5761 Gigabit Ethernet Interface (14E4:1681) which should be supported and I'm using 10.12.6. I tried to set the MAC Adress using "sudo ifconfig en0 ether  XX:XX:XX:XX:XX:XX:XX" but this doesn't work.

**Comment by chris1111** [comment]
> Sometimes my Hackintosh gets an MAC Adress and sometimes it says "00:00:00:00:00:00" instead of the original MAC Adress. I have an NetExtreme BCM5761 Gigabit Ethernet Interface (14E4:1681) which should be supported and I'm using 10.12.6. I tried to set the MAC Adress using "sudo ifconfig en0 ether XX:XX:XX:XX:XX:XX:XX" but this doesn't work.

Did you try to setup Mac adress with Clover configurator?
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu500.png)

**Comment by Dniel97** [comment]
In Clover I'm using an valid ROM Adress instead of "UseMacAddr0".

**Comment by chris1111** [comment]
Si try to remove this in Smbios

**Comment by chris1111** [comment]
So try to remove this setup in smbios

**Comment by Dniel97** [comment]
Should I remove my predefined ROM Adress or should I use "UseMacAddr0"?

**Comment by chris1111** [comment]
Try both 
First try usemacaddr0

**Comment by Dniel97** [comment]
I switched to "UseMacAddr0" and now ROM is my real MAC Adress, but in System Preferences it is still "00:00:00:00:00:00".

**Comment by chris1111** [comment]
> I switched to "UseMacAddr0" and now ROM is my real MAC Adress, but in System Preferences it is still "00:00:00:00:00:00".

Dont use the Real Mac ROM, Create your SMBIOS with Clover Configurator

**Comment by Dniel97** [comment]
Sry, I meant ROM is my Ethernet MAC Address, as it should be, but in System Preferences it is still "00:00:00:00:00:00" instead of the ROM Adress.

**Comment by chris1111** [comment]
> Sry, I meant ROM is my Ethernet MAC Address, as it should be, but in System Preferences it is still "00:00:00:00:00:00" instead of the ROM Adress.

Post here config.plist without Serial Number (XXXXXXXXXXX)

**Comment by Dniel97** [comment]
Here is my config.plist
[config.plist.zip](https://github.com/chris1111/BCM5722D/files/2871956/config.plist.zip)

**Comment by chris1111** [comment]
> Here is my config.plist
> [config.plist.zip](https://github.com/chris1111/BCM5722D/files/2871956/config.plist.zip)

Make a test with this config
[config.plist.zip](https://github.com/chris1111/BCM5722D/files/2871976/config.plist.zip)

**Comment by Dniel97** [comment]
Still the same.

![bildschirmfoto 2019-02-16 um 15 05 00](https://user-images.githubusercontent.com/6324072/52900911-b5047a80-31fc-11e9-8a10-5233718779b3.png)

**Comment by chris1111** [comment]
> Still the same.
> 
> ![bildschirmfoto 2019-02-16 um 15 05 00](https://user-images.githubusercontent.com/6324072/52900911-b5047a80-31fc-11e9-8a10-5233718779b3.png)

Did you try delete NetworkInterfaces.plist in Library/Preferences/SystemConfiguration/NetworkInterfaces.plist
then  remove all network in preferances System / Network

![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu507.png)
then reboot

**Comment by Dniel97** [comment]
I'm using your config.plist, deleted /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist and removed every Network. After rebooting and adding Ethernet to Network interfaces, the MAC Adress is still missing.

**Comment by Dniel97** [comment]
Today a message appeared, that something has changed an I need to reenter my Password and now my MAC Address is correct.
![bildschirmfoto 2019-02-22 um 13 20 25](https://user-images.githubusercontent.com/6324072/53242863-56c91300-36a6-11e9-8ffe-9bec01dca17c.png)
