### ISSUE TITLE
Cable Unplugged on BCM5709C

### ISSUE THREAD

**Issue by relghub** [chris1111/BCM5722D#3]
I have made a clean install of High Sierra 10.13.6. But I can't use the Internet, because vanilla OS doesn't detect my network adapter based on BCM5709C. I downloaded your kext and patched for using with my network chip, then installed it via Kext Utility and rebooted. But, after reboot, Network Preferences show "Cable Unplugged", when it is plugged. I deleted networkpreferences.plist and network profiles - no result. Full boot log is attached.
[system_logs.logarchive.zip](https://github.com/chris1111/BCM5722D/files/4892354/system_logs.logarchive.zip)

Thanks.

**Comment by chris1111** [comment]
What is the motherboard you have?
Show me a picture of **PCI List** with DCPIManager
![Capture d’écran, le 2020-07-08 à 14 21 04](https://user-images.githubusercontent.com/6248794/86955903-53f98180-c126-11ea-8f3a-c6e1e5bc8d79.png)

[DPCIManager.zip](https://github.com/chris1111/BCM5722D/files/4892519/DPCIManager.zip)

**Comment by relghub** [comment]
> What is the motherboard you have?

Motherboard is ASRock P55 Pro/USB3 (I turned off Realtek network chip because it doesn't work).

> Show me a picture of PCI List

Here you are.
![dpci](https://user-images.githubusercontent.com/57571132/86970597-4a990500-c178-11ea-83b1-560335cec221.png)

**Comment by chris1111** [comment]
Realtek Chip Works you need this Package Then select Release 
[RealtekRTL81xx-0_0_90.pkg.zip](https://github.com/chris1111/BCM5722D/files/4893502/RealtekRTL81xx-0_0_90.pkg.zip)

**Comment by chris1111** [comment]
BCM5709C I don't think is support on macOS ?

**Comment by relghub** [comment]
> Realtek Chip Works

No. This chip is dead on my MB, because it can't find network on Windows, when I tried to use it on Mac, it showed Self-Assigned IP with any kexts and drivers.

**Comment by relghub** [comment]
> BCM5709C I don't think is support on macOS ?

Natively - no, of course. But I think it's possible to patch the kext to initialize this chip.

**Comment by chris1111** [comment]
Wait!

**Comment by chris1111** [comment]
I have inject your device ID in this kext
[BCM5722D.kext.zip](https://github.com/chris1111/BCM5722D/files/4898668/BCM5722D.kext.zip)
