### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by hackintosh0** [chris1111/BCM5722D#4]
I updated macos mojave to it's latest security update and it stopped working.
I tried to boot with -v and there's no output from the kext. I can see the ethernet card in DPCI Manager, but it's not working.

Ethernet Card: BCM5761 - 14e4:1681
PC: Dell T3500

**Comment by chris1111** [comment]
Thanks to report I will see

**Comment by hackintosh0** [comment]
Something strange happened, I enabled my second disk in bios which has catalina on it and when booted into mojave ethernet connected.
