### ISSUE TITLE
Stop working in big sur

### ISSUE THREAD

**Issue by ming0352** [chris1111/BCM5722D#5]
Yesterday I have updated my system form Catalina to Big Sur(clean install),and the Ethernet card can’t work.
it’s seems Big Sur has modify IONetworkingFamily.kext so that the system can’t recognize the Ethernet card.

BCM57765-b0  0x14e4  0x16b5
Acer v3-571g

**Comment by chris1111** [comment]
were did you install the kext ?

**Comment by ming0352** [comment]
It’s not working too when I upgrade Catalina from 10.15.6 to 10.15.7. But when I replace the older IONetworkingFamily.kext and the problem was solved.
I use the newest kext from the release page and loaded by opencore 0.6.3,but I can’t replace the IONetworkingFamily.kext because Big Sur has  added new security protection ,so I  can’t mount S/L/E,despite I had disable SIP.

**Comment by chris1111** [comment]
Maybe try to follow this 
https://www.insanelymac.com/forum/topic/345905-how-to-make-root-folder-writable-in-big-sur/

**Comment by Mirec32** [comment]
Hi, can you share opencore files for Catalina? I have an Acer V3 571G, but it doesn't work...
