### ISSUE TITLE
Need to support bcm5720 14e4:165f!

### ISSUE THREAD

**Issue by iha3ker1920** [chris1111/BCM5722D#6]
Need this to support bcm5720 14e4:165f model... thank you!

**Comment by YIN-Renlong** [comment]
I attempted to utilize the driver available at https://www.tonymacx86.com/threads/bcm5761.309298/ BCM5722D-V-2.3.7. The Ethernet card is identified, but it cannot function correctly.

The detailed information is available here, with the same issue illustrated from my side.: https://www.tonymacx86.com/threads/hp-microserver-gen8-usb-now-working-built-in-bcm-ethernet-non-functioning.223775/

**Comment by iha3ker1920** [comment]
Ok, thank you for your efforts!!!
